### ISSUE TITLE
calling firebase.initializeApp(...) creates ~ 2 event listeners / seconds from then on (Chrome)

### ISSUE THREAD

**Issue by ncodefun** [firebase/firebase-js-sdk#1420]
* Operating System version: Win10 64bit
  * Browser version: Chrome 71
  * Firebase SDK version: 5.5.8 & 5.7.0
  * Firebase Product: firebase-app

Make an html file with boilerplate, and in head:

1. Load these scripts: firebase-app.js & firebase-auth.js
2. Put this in a script with your project infos:
```javascript
firebase.initializeApp( {
	apiKey: '...',
	authDomain: '...',
	databaseURL: '...',
	projectId: '...',
	storageBucket: '...',
	messagingSenderId: '...'
})
```
3. Open html file in Chrome and open devTools -> performance monitor
see the number of event listeners constantly rise until garbage collection.

**Comment by Feiyang1** [comment]
@wti806 There appears to be a memory leak in auth. Can you please take a look?

**Comment by FallenRiteMonk** [comment]
@Feiyang1 this does not seem to be leak in auth. I can reproduce the issue just by importing firebase and calling the initializeApp function.

This seems to be a issue for long running applications. Would be nice to get some feedback, a workaround or preferably a fix.

**Comment by Feiyang1** [comment]
initializeApp automatically initialize Auth if Auth is being imported.
The number of listeners only increases when Auth is included. I can see it right away (don't need to be long running).
@FallenRiteMonk Maybe you are talking about a different issue?

**Comment by FallenRiteMonk** [comment]
@Feiyang1 no it should be exactly this one as I can see the 2 listeners per second being added in the chrome dev tools. I didn't know that, then it might still be auth that makes the problem as i import all of firebase. 
I'll try to analyse it furter, but in the mean time, is there something I can do to prevent it? Or do I have to wait for a fix (or even try to fix it my self and make a PR)?

**Comment by FallenRiteMonk** [comment]
@Feiyang1 you were right, it is a auth problem.

I have create a small reproduction of the problem,
code: https://stackblitz.com/edit/js-1bvnlf
test page: https://js-1bvnlf.stackblitz.io/

Steps: Open test page, open chrome dev tools, do a performance analysis over a couple of seconds

result:
![screenshot-firebase-mem-leak](https://user-images.githubusercontent.com/8779846/54776291-165ea580-4c10-11e9-817a-3f89ff20d93a.png)

**Comment by grant1842** [comment]
I fixed my issue with this by leaving Firebase and moving to AWS/NodeJS/MongoDB.  You'd be surprised at how much more control and options you have.  Auth is easy and NodeJS is what the "Firebase Functions Server" is.  Applying "security rules" to db access is way better as you have more control.  The best part is you're not loading any bloated up client libraries in your javascript.  You make asynchronous http calls and process the return.  If you're going for the "realtime" effect then socket.io is easy enough to implement and you're all set.

This is such a critical problem that was reported months ago.  Having a Firebase website crash client browsers for months until they fix it isn't something I plan on building a product around.

**Comment by obirider** [comment]
Any progress here? I have the same problem without any workaround! 

I have a long running monitoring app which starts to become slow and laggy due to this problem.
On Safari and Edge it got even as far as killing the whole browser tab after a few hours of running.

**Comment by bojeil-google** [comment]
This behavior existed since we launched the SDK. We set polling functions to listen to indexedDB changes to detect cross tab changes (user opens multiple tabs and either signs in or signs out or modifies the user in one tab, etc). The session will be synchronized across the tabs.
Unfortunately there are no cross browser reliable API to detect changes on indexedDB. There is an [experimental API](https://github.com/WICG/indexed-db-observers/blob/gh-pages/EXPLAINER.md) for this but until it is a W3C standard, we can't use it.

If you don't require this functionality, our V6 modularization efforts will allow you to switch to `localStorage` which has storage events for detecting changes cross tabs, and possibly will provide you the ability to define your own storage interface.

**Comment by shaunwallace** [comment]
Are there any plans to revisit this as I can see that it is still an open issue even with the latest version as the event listeners are increasing linearly without bounds it would seem.

**Comment by tolotrasamuel** [comment]
Is there any work around for this issue ? Anything really? 
This is **critical bug** for our app because it requires the tab to be always open for more than 20 hours

**Comment by joscmw95** [comment]
Isn't this fixed in #1121?

**Comment by wti806** [comment]
The issue that 2 listeners are added per second has already been fixed. You can try from here: https://js-1bvnlf.stackblitz.io

**Comment by ncodefun** [comment]
This issue still exists for me. @wti806 The demo too shows this isn't fixed.

**Comment by tabtrader** [comment]
Looks like it's fixed at 0.5.0

**Comment by elektronik2k5** [comment]
Seriously? A confirmed, reproducible memory leak at a rate of ~ 5MB a minute in Google's official SDK for A YEAR AND A HALF???? From v5 (first report) to the latest `firebase@7.14.3`, over 3 major versions? For a product which is meant for SPAs?

![image](https://user-images.githubusercontent.com/1078554/81612611-65036c00-93dd-11ea-8814-ab1e324f095c.png)

I'm speechless. I wouldn't have complained about any open source product which is maintained by volunteers and would have dug in myself to fix. But Firebase is maintained by paid google employees for a proprietary product. I mean, 99% of Firebase apps on the web require auth and they are all affected. :exploding_head:

**Comment by joscmw95** [comment]
I thought the leak is fixed and the linearly increasing listener count is expected behavior and will be removed upon GC? https://stackoverflow.com/a/59259004/9758160

**Comment by elektronik2k5** [comment]
@joscmw95 thanks for the very detailed info. Basically, you're saying that Chrome DevTools real time memory usage metrics are unreliable? If true, it seems like an even worse problem to me cause it means that those numbers are basically useless. I find it hard to believe that such a fundamental issue would be overlooked by Blink, Chrome and DevTools engineers.

I wish Firefox had similar/better tools to monitor these metrics so we could compare the two.

As for the bug itself, even though the event listeners and memory are periodically cleaned, the current behaviour seems broken. I mean, even if for some good reason it can't be prevented, then at least the cleanup should be triggered much more often.

**Comment by MeghaB** [comment]
The memory leak in the original issue [has been fixed](https://github.com/firebase/firebase-js-sdk/pull/1121).  What we're seeing now is normal memory growth that is eventually garbage collected.  We'd like to eventually reduce our total memory usage but that's long-term and out of scope for this issue.

**Comment by MeghaB** [comment]
@elektronik2k5 The tone of your feedback is unhelpful and not up to the standards of the Firebase community.  If you find a bug in the future please open a new issue and follow the guidance of the issue template and contributing guide

**Comment by jtestard** [comment]
@MeghaB I am afraid @elektronik2k5  is just saying what everybody is thinking. On our end, this bug makes it impossible to use the firebase js client on our browser side web app (a game). The memory leak eventually makes the game unplayable. We had to resort to reverting to server side authentication as as result, and lost a lot of time.

**Comment by elektronik2k5** [comment]
Adding here parts of my correspondence with Firebase support for the sake of transparency:

> Although the issue was closed, claiming that it is resolved, it clearly isn't.
>
> You can observe the memory leaking on the documentation page:
> 1. Open https://auth-service-worker.appspot.com/?authuser=0.
> 1. Open **Performance monitor** in **DevTools** and enable tracking the **JS event listeners** count
> 1. Observe listener count increasing at a rate of 2 per second
> 1. Open Chrome's **Task Manager**, find the relevant tab
> 1. Observe **Memory footprint** and **JavaScript memory** increasing continuously
>
> The "fix" does clear the listener count and memory usage every few minutes - but during that interval the memory increases continuously. I'd categorize that as a temporary hotfix/bad workaround and not a proper resolution of the root root cause. If there's no resources for a proper fix, then at the very least the memory clearing should be triggered every few seconds instead of every few minutes.
>
> I mean, really, on the one hand Google advocates for using best practices on the web and offers tooling like DevTools and Lighthouse - on the other hand this bug is affecting **every single Firebase web app** - wasting CPU, memory and as a result device battery. Just the few minutes it took me to write this response the event **handler count has reached from 100 to over 2000** and the **memory consumption from 60MB to 90MB**.
>
> This can't possibly be considered as "fixed" and I believe Firebase users deserve better.

Responding later to a request for more details and screenshots:

> Looking at your screenshot, the event listener count is clearly seen constantly increasing. That's exactly the problem I'm pointing out. The other way the issue is observable is in memory usage.
>
> Here, a few seconds after opening a the tab in question:
> ![image](https://user-images.githubusercontent.com/1078554/82376542-91913680-9a22-11ea-8881-1f0d7c04ecdb.png)
> Memory footprint is just under 37MB and 8,600/5,300k JavaScript memory - highlighted in the selected tab of the task manager.
>
> Same tab after just 5 minutes:
> ![image](https://user-images.githubusercontent.com/1078554/82376720-cf8e5a80-9a22-11ea-9041-7837ebe15914.png)
> Memory footprint is just over 53MB and 8,900/5,900k JavaScript memory.
>
> And again, after a few more minutes:
> ![image](https://user-images.githubusercontent.com/1078554/82376787-ed5bbf80-9a22-11ea-8c26-4fc0c8f962ba.png)
> Memory footprint is at 87MB and 9,900/7,400k JavaScript memory.
> 
> Should I go on? I mean it is an idle tab, which I opened less than 20 minutes ago.
> At some point it does reset. But this isn't "fixed" or normal.

I think I'm out of quota for images per thread here, so _<inset "THIS IF FINE" meme here>_. :sweat_smile:

**Comment by elektronik2k5** [comment]
Adding some new information I discovered today when collecting data for Firebase support, which are working on this issue.

On an older (but still modern) laptop the CPU load 2 hours after opening the same tab looks like so:
![image](https://user-images.githubusercontent.com/1078554/82756457-b7c82500-9dda-11ea-8be9-1cd06926a0f1.png)

And here you can clearly see the moment I closed that single tab:
![image](https://user-images.githubusercontent.com/1078554/82756477-d3cbc680-9dda-11ea-85a8-e44d365df20a.png)

My other, newer laptop tells a similar story:
![image](https://user-images.githubusercontent.com/1078554/82756512-fe1d8400-9dda-11ea-83ac-aabf20fcceea.png)
I closed the tab at around the 35s mark - though it is much harder to spot.

**Comment by sam-gc** [comment]
## Why is this happening?
The Firebase Auth web SDK supports three different types of persistence (in-memory, session, and non-session), backed by four different data stores (JS map, `sessionStorage`, `localStorage`, and `indexedDB`). By default, when you call `getAuth()`, the SDK is configured to use the first available storage, starting preferentially with `indexedDBLocalPersistence`:
https://github.com/firebase/firebase-js-sdk/blob/df8604e4dada5874ce0513e3376ded130b6231b4/packages/auth/src/platform_browser/index.ts#L80-L87

Indexed DB, unlike browser local storage, does not have [storage event](https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event) support. In order to maintain cross-tab synchronization (meaning if you sign-out in one tab you should sign out in all tabs) it is required to _poll indexedDB_. The SDK does this every 800ms:
https://github.com/firebase/firebase-js-sdk/blob/df8604e4dada5874ce0513e3376ded130b6231b4/packages/auth/src/platform_browser/persistence/indexed_db.ts#L405-L408

In order to read data from Indexed DB, you must create a DB request, [_and attach event listeners_](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#getting_data_from_the_database) to that request for success and error outcomes. The 2 listeners per 800ms you’re seeing come from this code:
https://github.com/firebase/firebase-js-sdk/blob/df8604e4dada5874ce0513e3376ded130b6231b4/packages/auth/src/platform_browser/persistence/indexed_db.ts#L65-L70

These request objects are transient by nature; we attach event listeners, which will be cleaned up in the same GC lifecycle as the request objects themselves. We do not retain the DB requests any longer than necessary, but we have no control over when the GC runs.

### Why `indexedDB`?
`indexedDB` is available to service workers whereas `localStorage` is not. In order for service workers to seamlessly use Firebase Auth when the parent site is signed in, we chose `indexedDB` to share Auth state.

### If there’s GC why do the listener counts keep rising?
We believe this is an unrelated artifact of the Chrome developer tools. See the discussion under the heading “Regarding linearly increasing listener number” in the StackOverflow thread linked earlier: https://stackoverflow.com/questions/59101363/angular-firebase-app-crashes-after-20-hours-with-1-gigabyte-of-memory-allocatio/59259004#59259004 and the linked Chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=576302

## I really, really care about this, how can I avoid it?
Luckily modular SDK versions 9+ allow developers to precisely configure which backing data store they’d like for persistence. If you’re not using service workers, you can configure your app to only use `localStorage`. Since the `indexedDB` is never loaded, the polling never happens.

Here’s a snippet for initializing Auth to use only localStorage:
```js
import {initializeAuth, browserLocalPersistence, browserPopupRedirectResolver} from 'firebase/auth';

const auth = initializeAuth(app, {
  persistence: [browserLocalPersistence],
  popupRedirectResolver: browserPopupRedirectResolver,
});
```

**Note:** if you take this approach you won’t be able to synchronize Auth with a service worker.

For more information about customizing Auth dependencies, check out the docs: https://firebase.google.com/docs/auth/web/custom-dependencies 

We believe this and [related](https://github.com/firebase/firebase-js-sdk/issues/4130) issues should remain closed.
