### ISSUE TITLE
FR: Firebase function support for Async/Await 

### ISSUE THREAD

**Issue by lsbyerley** [firebase/firebase-js-sdk#1708]
Are there any plans to support async/await when calling firebase functions? For example..

```javascript
async login() {
  try {
    const loginRes = await firebase.auth().createUserWithEmailAndPassword(email, password);
    //steps after logging in
    
  } catch(err) {
    //error handling
  }

}
```

**Comment by hsubox76** [comment]
Good news, you should be able to upgrade to a Node 8 runtime for functions (which supports async/await): https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version

That page says it's in beta but it's officially supported (and recommended) now.

**Comment by lsbyerley** [comment]
@hsubox76 awesome! thanks!

**Comment by lsbyerley** [comment]
@hsubox76 I updated the engines variable in my package.json and compiled. The async/await functions seem to work, but they generate an error in the console.

**Comment by hsubox76** [comment]
What is the error?  Do any of the suggestions here (https://github.com/firebase/firebase-functions/issues/319) help?

**Comment by lsbyerley** [comment]
Here is an example of how I'm using async/await to call the `sendPasswordResetEmail()` function. This is in a vue method.

    async resetPassword() {
      try {
        const resetReq = await fb.auth.sendPasswordResetEmail(this.passwordForm.email);
      } catch(err) {
        this.handleErrorCode(err.code)
      }
    }

And this is what I'm seeing in console when intentionally forcing an error by leaving the email field blank. It seems like its not "catching" the error. On a successful request, nothing appears in the console, as expected

<img width="927" alt="Screen Shot 2019-04-25 at 6 52 41 PM" src="https://user-images.githubusercontent.com/3066258/56773347-b5386d80-678b-11e9-9a6d-4a1b13836d07.png">

**Comment by hsubox76** [comment]
Oh wait, I think we misunderstood your question.  You're not using Firebase Cloud Functions (https://firebase.google.com/docs/functions), you're asking about just calling a Firebase auth method from the browser client?  Sorry to have missed that.

In any case, this error doesn't seem related to async/await.  I was able to reproduce it, and the same error seems to happen even if using promises.  I'll keep looking into it separately (there may be something about the Auth code I don't understand), but I will close this issue since the async/await topic has been resolved.

**Comment by lsbyerley** [comment]
@hsubox76 my apologies for not being more clear.. regardless, thank you for the help!

**Comment by hsubox76** [comment]
Sorry, I corrected my post above.  This uncaught error does happen with async/await only and not with promises.

**Comment by JimPatterson** [comment]
@hsubox76 It looks like you closed this on Apr 26 thinking that the problem was resolved, but then realized that it was not without re-opening it.  I am seeing the same scenario.  The Promise returned by `auth.signInWithEmailAndPassword` has some kind of internal setTimeout that is running and if you get an error but don't call the `.catch` method (instead using await to turn it into a try), the you get the `Uncaught` error reported in the console.

Should this be re-opened?  Should I report the problem on a different issue?

**Comment by skylite21** [comment]
I have the same issue. If I use async/await I can catch the error but the ugly Uncaught M still appears in the console, the same way as it does for @lsbyerley This issue should be reopened.

**Comment by hsubox76** [comment]
I think the title and beginning comments of this issue make it too confusing, can you create a new one centered specifically on using `async/await` with Auth methods?

**Comment by skylite21** [comment]
#1881
