### ISSUE TITLE
Promise never resolves when performing an action on a Firestore DB after calling auth.createUserWithEmailAndPassword

### ISSUE THREAD

**Issue by nefarioustim** [firebase/firebase-js-sdk#3218]
* Operating System version: MacOS Mojave 10.14.6
  * Browser version: Firefox 78, Chrome 84, Safari 13.1.1
  * Firebase SDK version: 7.15
  * Firebase Product: auth, firestore

When attempting to follow a call to `auth.createUserWithEmailAndPassword` with code that updates or creates a Firestore document (in my initial case it was a `firestore.collection().doc().set()`, but in testing it was the same for an `.update()`), the returning Promise never resolves and simply hangs.

Here is a simplified example of the Vuex actions I am calling in my code that exhibit this issue:

```javascript
    signUserUp ({ dispatch, commit }, payload) {
      const $app = this.$app
      commit('setLoading', true)
      commit('clearError')

      return fb.auth
        .createUserWithEmailAndPassword(payload.email, payload.password)
        .then(userRef => {
          $app.logInfo('Created auth user', {'email': payload.email})

          return dispatch("createAccount", payload)
        })
        .catch(error => {
          commit('setLoading', false)
          commit('setError', error)
          $app.logError('Error signing up user', {error: error.message})
        })
    },

    createAccount({ commit, dispatch }, payload) {
      const $app = this.$app
      return fb.db.collection(COLLECTION)
        .doc(payload.account)
        .set({
          'created': new Date().getTime(),
          'updated': new Date().getTime(),
          'active': true,
          'account': payload.account,
          'legalName': payload.legalName,
          'country': payload.country,
          'currency': payload.currency,
          'industry': payload.industry,
          'email': payload.busemail || payload.email, // Allow for signup form
          'about': payload.about,
          'tags': payload.tags,
          'type': payload.type
        })
        .catch(error => {
          commit('setLoading', false)
          commit('setError', error)
          $app.logError('Error creating account', {error: error.message})
        })
    }
```

I have managed to temporarily resolve this issue by rolling back to version 7.14 of the SDK, but obviously I'm interested in a more longterm fix that allows me to continue upgrading the SDK.

Possible related to #3120 and raised following comments there.

**Comment by schmidt-sebastian** [comment]
@nefarioustim Thanks for reporting. 

This is likely fixed in v17.15.1, which includes https://github.com/firebase/firebase-js-sdk/pull/3184. Do you mind verifying your issue with this version?

**Comment by gragland** [comment]
@schmidt-sebastian I'm having the same problem and v17.15.1 didn't fix it for me. In case it's helpful to know, I'm able to work around the issue by wrapping the write in a short setTimeout. As long as it gets called after `onAuthStateChanged` fires (which seems to always be a few ms after `createUserWithEmailAndPassword` completes) then the write succeeds.

**Comment by nwaughachukwuma** [comment]
Thanks, @gragland. @schmidt-sebastian this also happens when using social auth (redirect or popup) and I had made a [comment](https://github.com/firebase/firebase-js-sdk/issues/2923#issuecomment-645127195) in #2923 (although closed).

**Comment by nefarioustim** [comment]
Hey @schmidt-sebastian; apologies for the delay, but I can confirm I am experiencing the same issue with 17.5.1. :(

**Comment by sunteago** [comment]
Experiencing the same issue after calling auth.createUserWithEmailAndPassword, had to go to v7.14.4 for the moment that seems to work fine

**Comment by pelagaggi** [comment]
I am experiencing the same issue on a ReactJS based application, the promise returned the first time I created a user but after that never returned, I have tried downgrading 

After downgrading from 7.16.1 changing in package.json and index.html
```JavaScript
package.json
    "firebase": "7.14.4",
````
```html
  <!-- The core Firebase JS SDK is always required and must be listed first -->
  <script src="https://kiyo-ngo-sinergia.firebaseapp.com/__/firebase/7.14.4/firebase-app.js"></script>

  <!-- TODO: Add SDKs for Firebase products that you want to use
        https://firebase.google.com/docs/web/setup#available-libraries -->
  <script src="https://kiyo-ngo-sinergia.firebaseapp.com/__/firebase/7.14.4/firebase-analytics.js"></script>
```
I notice that my URL was showing sensitive info which suggested that could be something else than firebase.
```
?firstName=xxxx&lastName=xxxx&email=xxxx%40gmail.com&password=xxxx&policy=
```
It turns out that I was not preventing an event propagation on my login Form submit. After fixing that I Changed Back to version 7.16.1 and now my promise is returning.

Hope this helps someone

**Comment by sunteago** [comment]
I was also working with React. Now I upgraded to v7.16.1 and I am no longer experiencing this problem, I think it's now solved.

**Comment by LandazuriKastilloCode** [comment]
Thanks sunteago indeed it is no longer present on v7.16.1. I was starting to lose my mind with this bug.

**Comment by Hubiwan** [comment]
Not trying to necro this one, but looks like this issue has been re-introduced (currently using v8.6.3). Same behaviour as described by @gragland, wrapping subsequent writes to Firestore inside a setTimeout does the trick, but still quite annoying to add back this ad hoc hacky wrapper.

**Comment by schmidt-sebastian** [comment]
This should be fixed by https://github.com/firebase/firebase-js-sdk/pull/4971

**Comment by rrluthi** [comment]
This is happening on the beta 9.0.0-beta.3 as well.
