### ISSUE TITLE
"Create index" link not provided (firebase 8.7.1)

### ISSUE THREAD

**Issue by charles-allen** [firebase/firebase-js-sdk#5152]
### Describe your environment

  * Operating System version: **MacOS 11.4 (20F71)**
  * Browser version: **Node v14.16.0**
  * Firebase SDK version: **`firebase` 8.7.1**
  * Firebase Product: **Firestore**

### Describe the problem

I wrote a query that requires an index. It errors with this message (which doesn't contain a link to create the index):

- Expected: link to create index
- Actual: no link

![Screen Shot 2021-07-15 at 13 03 57](https://user-images.githubusercontent.com/31621095/125737319-edf20d0f-708c-4573-81fc-a9f6cc869836.png)

#### Steps to reproduce:

- Write a query with where/orderBy on multiple fields

#### Relevant Code:

```javascript
const query = db.collection('iterations')
  .where('courseCode', '==', code)
  .orderBy('iterationCode', 'desc')
  .limit(1)
  .get()
```

**Comment by DharmarajX24** [comment]
It seems that only the Client SDKs are not returning index creation links. The Admin SDK still throws an error with the link. You can  try running your query in Firebase Functions emulator and get the link from there. I've posted a similar answer on [Stackoverflow](https://stackoverflow.com/questions/68388195/firebase-index-required-but-no-link-provided/68388387#68388387).

**Comment by looptheloop88** [comment]
Hi @charles-allen, thanks for the report. I was able to replicate the issue. Let me bring this matter to the attention of our engineers here and update this thread if I have any information to share.

**Comment by dreamerchandra** [comment]
I guess the even older versions of firebase library aren't providing url
![image](https://user-images.githubusercontent.com/17010408/125831386-cdcd0208-b4a3-4c35-bdd2-020ad034c205.png)

**Comment by looptheloop88** [comment]
We're also seeing similar reports on other platforms. It seems to be a backend issue and currently being tracked internally. For reference, see b/193768583.

**Comment by jbistis** [comment]
We are encountering this too for all required indexes not built.
"firebase": "^8.7.1",
"firebase-admin": "^9.11.0",
"firebase-tools": "^9.16.0",

**Comment by madisonatamea** [comment]
any updates?

**Comment by jaimejangg** [comment]
Got the same error, any updates ?

**Comment by jailsondamasceno** [comment]
Looks like we're going to stick with this problem and create the indexes manually :(

**Comment by lxieyang** [comment]
Any updates? It breaks my app completely.

**Comment by charles-allen** [comment]
Unless your app is automatically creating missing indexes (which sounds like a questionable design decision), this is not breaking your app.

Just create the index manually in Firebase Console.

**Comment by r-ndom-developer** [comment]
I'm having the same issue and for some reason I can't even create an index manually from the console.

**Comment by DharmarajX24** [comment]
> Looks like we're going to stick with this problem and create the indexes manually :(

I mean you can still create those click to create index links from Admin SDK in emulator @jailsondamasceno  👀

**Comment by Lazy-Developer-here** [comment]
Hi ,

Any update on this. 

FYI If manually create on console it also not working as intended.

**Comment by charles-allen** [comment]
> FYI If manually create on console it also not working as intended.

This is **not what I'm seeing**. I made an index manually using the console and **my code now runs fine**.

If you're having problems with the console you should open an issue with details, screenshots, etc.

**Comment by dionkas** [comment]
Also having troubles with this. I can create an index via the console but it still does not recognise it once it is built, giving me the same error.

**Comment by jailsondamasceno** [comment]
@dionkas Hire, likewise

**Comment by BluebambooSRL** [comment]
Same problem...

**Comment by DualPeaks** [comment]
Same issue and its really costing me a lot of time .... Please fix

**Comment by charles-allen** [comment]
@r-ndom-developer @Lazy-Developer-here @dionkas @jailsondamasceno - I have only reported the lack of link in the error message. If you have an additional issue you must provide:
- query you're executing
- index you made (screenshot)
- error message

In my case, I was able to make an index & run my code. I am not blocked at all. Additionally this was for a class. My students were also able to make the index successfully (though many of them first made typos in the collection name, field names, or direction). In all cases we corrected the index and the code ran successfully.

**Comment by dionkas** [comment]
@charles-allen **we are reporting the same issue**. Not creating indexes via firebase’s “create link” because that is not provided now. 
Also, failure to have working indexes when creating via the console is a side effect of this bug you have described. Threads on github are there to discuss what people have tried and what worked or didn’t work to ultimately fix a problem.

**Comment by charles-allen** [comment]
> **we are reporting the same issue**
> ...
> Also, failure to have working indexes when creating via the console is a side effect of this bug you have described

No... not also. **This is not a side-effect of the bug I reported.**
I have repeatedly reported that my indexes, created manually in Firebase Console, are working.

**Comment by charles-allen** [comment]
> **we are reporting the same issue**
> ...
> Also, failure to have working indexes when creating via the console is a side effect of this bug you have described

I'm discussing the "also". **I don't think broken indexes are not a side-effect of the bug I reported.**
I have repeatedly reported that **my indexes are working** (when created manually in Firebase Console).

If you have an "also" issue, show it here (or make a new issue).
I suspect that your indexes are broken because you created them incorrectly.

**Show what you tried. I don't think you're blocked. I don't think your broken index is related. We can fix it now.**

**Comment by Lazy-Developer-here** [comment]
Hi @charles-allen  ,

Does firestore indexing working for you? able to retrive data for multiple conditions in single query.

For Single query it is working if you add multiple  conditions with already created document working?

**Comment by charles-allen** [comment]
> Does firestore indexing working for you?

Yes

> able to retrive data for multiple conditions in single query.

Yes, for the query in my original post

> with already created document working?

Yes, the documents existed before I made the index

For reference, here is my index:

![Screenshot_20210720_163901](https://user-images.githubusercontent.com/31621095/126300215-44bcc191-79ed-4afe-a026-d5bce29f320f.jpg)

![Screenshot_20210720_164008](https://user-images.githubusercontent.com/31621095/126300221-9955caaf-0e5d-43ef-b343-fe056d533e4f.jpg)

**Comment by charles-allen** [comment]
Note: I only replicated this once. From memory my code errored, then I only added the index (and nothing else), and then it worked.

But my memory isn't perfect! Maybe I've missed something or perhaps my example is unusual.

**Comment by macmatrix** [comment]
Same problem here. I do not get the link from the console and I keep getting the error after creating the index manually.

this is my query

```
_firestore
          .collection('photos')
          .where('seen', isEqualTo: '')
          .where('uid', isNotEqualTo: appData.user.uid)
          .where('interest', isEqualTo: appData.userInterest)
          .limit(1)
          .get()
          .then((QuerySnapshot snapshot) async {

        if (snapshot.docs.isNotEmpty) {//
```
 and this is my index

<img width="1018" alt="Screenshot 2021-07-20 at 10 48 54" src="https://user-images.githubusercontent.com/54081639/126306591-f6f339a1-1e2e-478a-bc1b-078a4202016c.png">

What am I doing wrong?

**Comment by charles-allen** [comment]
> this is my query
> 
> ```
> _firestore
>           .collection('photos')
>           .where('seen', isEqualTo: '')
>           .where('uid', isNotEqualTo: appData.user.uid)
>           .where('interest', isEqualTo: appData.userInterest)
>           .limit(1)
>           .get()
>           .then((QuerySnapshot snapshot) async {
> 
>         if (snapshot.docs.isNotEmpty) {//
> ```

I guess `seen`, `uid`, and `interest` are all string fields?

**Comment by macmatrix** [comment]
> I can't see anything obvious (though I confess to not being an index pro!). I guess `seen`, `uid`, and `interest` are all string fields? `interest` isn't an array?

They are all string. Note the uid has a "isNotEqualTo" operator

**Comment by charles-allen** [comment]
> Note the uid has a "isNotEqualTo" operator

Looks valid to me (but again, I'm no expert).

I think the orderBy in my example is significant. I think the where part and orderBy part use the index in a different way. I read on SO that the field being used to order must be last in the index (no such limitations on the ordering of where fields in your index). 

I also read that you can split indexes. I don't know the rules... but perhaps you could try 2 indexes: seen+uid, uid+interest.

One last observation... I can see you have another index on `photos` on `userId` rather than `uid`. Is it possible you just got your field name wrong (in both the query & index)?

**Comment by macmatrix** [comment]
Nope the names are correct. I am hopeless

**Comment by silicakes** [comment]
Happens on `v8.3.1` as well.

**Comment by schmidt-sebastian** [comment]
The problem has been fixed via an update to the backend.

**Comment by macmatrix** [comment]
The problem still persists in my app...

I keep getting this error

`[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: [cloud_firestore/failed-precondition] Operation was rejected because the system is not in a state required for the operation's execution. If performing a query, ensure it has been indexed via the Firebase console.`

**Comment by marlow-fawn** [comment]
> The problem has been fixed via an update to the backend.

When will this fix be available?

**Comment by AliciaAMT** [comment]
It is fixed already, but you may have to update Chrome and restart it. I had this problem yesterday, but after Chrome update and restart it works!

**Comment by sajitkhadka** [comment]
Still giving me the error! Not sure why the issue has been closed.
![image](https://user-images.githubusercontent.com/8060597/126379313-88c82d91-7cc9-4f92-b333-2c2c21320b4b.png)

**Comment by silicakes** [comment]
> The problem has been fixed via an update to the backend.

@schmidt-sebastian Still seeing it as well.

**Comment by miszmaniac** [comment]
> > The problem has been fixed via an update to the backend.
> 
> @schmidt-sebastian Still seeing it as well.

same here

**Comment by jailsondamasceno** [comment]
here too

**Comment by jailsondamasceno** [comment]
Hi guys, I did the cli deployment using the json file, and it worked.
![image](https://user-images.githubusercontent.com/65731201/126392242-28fe2218-da1a-458f-a916-e405f299a741.png)
****

**Comment by schmidt-sebastian** [comment]
I am confirming with the backend team to see when this issue should be fully mitigated. This is a server-side only issue and should not require any changes on your end.

**Comment by charles-allen** [comment]
> here too.
> It's totally broken.
> In my case it breaks when placing the order by.
> And if I don't put the order by, the error doesn't happen, which is also an error because I put a combination of 4 "where" and even though I didn't create an index, the error didn't appear, it made the call.

I guess all your where clauses are just equals. I think the indexes are only needed when you have inequalities (>, >=, etc), not-equals, not-in, ordering. 

Multiple equals conditions seems to work by default (did for my query with 2 equals only), I guess by combining the single indexes.

**Comment by charles-allen** [comment]
> The problem has been fixed via an update to the backend.

Thanks for the updates @schmidt-sebastian 

> schmidt-sebastian closed this

Suggest you update your DoD to include "fix fully deployed" to block closing public issues before the fix is available to everyone (it causes confusion closing it early; and none of us care about the issue's status on Github, only whether the fix is working).

**Comment by silicakes** [comment]
Confirmed working.
