### ISSUE TITLE
`OAuthProvider` is missing constructor

### ISSUE THREAD

**Issue by AgainPsychoX** [firebase/firebase-js-sdk#5392]
### Environment

  * Firebase SDK version: `9.0.0`
  * Firebase Product: `auth`

### Problem

Firebase Auth API v9 does not have `OAuthProvider` constructor, or at least in TypeScript typings.

API v9: https://firebase.google.com/docs/reference/js/auth.oauthprovider (no constructor or a way to get new instance `OAuthProvider`)

API v8: https://firebase.google.com/docs/reference/js/v8/firebase.auth.OAuthCredential (it's fine at v8)

Even comment docs suggest it should be there (:
![a](https://user-images.githubusercontent.com/23557839/131069746-ad3cd82c-4a5b-46e7-836d-f6744a2cc964.png)

I need it as I want to use OIDC (https://cloud.google.com/identity-platform/docs/web/oidc), but no constructor, no `addScope`.

**Comment by cungminh2710** [comment]
Yup `new OAuthProvider('apple.com')` won't work. [These workarounds](https://github.com/firebase/firebase-js-sdk/issues/5392#issuecomment-906938939) can be used in the meantime

**Comment by jpike88** [comment]
Just ran into this issue on Cordova:

```
const auth = getAuth(Environment.firebaseInstance);
			const provider = new GoogleAuthProvider();
			try {
				await signInWithRedirect(auth, provider, cordovaPopupRedirectResolver);
			} catch (error) {
				// swallow this, just return.
				return;
			}
			const result = await getRedirectResult(auth);
			const credential = GoogleAuthProvider.credentialFromResult(result);
			await this.handleSSOAuthResult(
				AuthProviders.Google,
				result.user.email,
				credential.idToken
			);
```

This should work but errors. Error is being caused here:
https://github.com/firebase/firebase-js-sdk/blame/509c18fbc1a0d4f85a0ca8c7cfef8e3b0f3183ec/packages/auth/src/platform_browser/strategies/redirect.ts#L95

**Comment by jpike88** [comment]
Also none of the above workarounds work for me, that assert still trips even when the console seems to be indicating that the OAuthProvider is a subclass of FederatedProvider...

This is broken and a critical issue for us

<img width="1192" alt="Screenshot 2021-08-30 at 3 24 02 PM" src="https://user-images.githubusercontent.com/9585787/131309455-afbc6865-f401-4d56-a9c3-e50c95712028.png">

**Comment by jpike88** [comment]
More investigating...

If I remove that above line from the vendor code and just force things through, a browser tab opens with this URL: 

https://auth.formpigeon.com/__/auth/handler?apiKey= API_KEY_GOES_HERE&appName=%5BDEFAULT%5D&authType=signInViaRedirect&v=9.0.0

obfuscated values: API_KEY_GOES_HERE

But it's a white screen with the text 'The requested action is invalid.'


But when I test on a working version (firebase@8.x), the url is this:

https://auth.aquipa.com/__/auth/handler?apiKey=API_KEY_GOES_HERE&appName=%5BDEFAULT%5D&authType=signInViaRedirect&providerId=google.com&scopes=profile&v=8.6.4&ibi=COM.COM.MYAPP&appDisplayName=APP_NAME&sessionId=SESSION_ID

obfuscated values: API_KEY_GOES_HERE, COM.COM.MYAPP, APP_NAME, SESSION_ID

**Comment by Feiyang1** [comment]
It is fixed in `9.0.1`.

@jpike88 Thanks for the report and investigation. It seems to be a different issue than the original one. Can you please open a new issue, so we can track it there properly?

**Comment by jpike88** [comment]
@Feiyang1 you're right, it's a different issue, just tried with 9.0.1 and still present. opened an issue at #5420
