### ISSUE TITLE
getDoc() is never resolved nor rejected

### ISSUE THREAD

**Issue by laurentpayot** [firebase/firebase-js-sdk#5402]
### [REQUIRED] Describe your environment

  * Operating System version: Ubuntu 21.04
  * Browser version: Chrome 92
  * Firebase SDK version: 9.0.0
  * Firebase Product: Firestore

Note that I'm running Firestore in a web worker.

#### Steps to reproduce:

`got doc` is never logged (see code below)

Everything was fine with the v9 beta. The official, non-beta release broke it.

#### Relevant Code:

```typescript
import {
    collection, doc, getDoc, writeBatch, updateDoc, deleteDoc, onSnapshot, query, limit
} from '@firebase/firestore'

/* … */

export default {

  /* … */

  // get user by user ID
  async getById(uid:string, db=defaultDb): Promise<User|null> {
    const userDoc = doc(db, 'users', uid)
    console.log("getting doc…")
    const userSnap = await getDoc(userDoc).catch(errorInfo(`user ${uid} fetching`))
    console.log("got doc")
    return <User>userSnap.data() ?? null
  }

  /* … */

}
```
Related to https://github.com/firebase/firebase-js-sdk/issues/5398?

**Comment by GaryAustin1** [comment]
I have been trying to start the conversion process from 8 and am seeing a similar issue with 9.0.0 in both compat mode and new mode.  Neither docRef.get() or getDoc seem to do anything (no debug messages with debug on, no network requests, no error, no return).  Auth and database seem to be working in compat mode on same project.  The database object and doc object seem to coming back with filled in data.

**Comment by dconeybe** [comment]
Hello @laurentpayot. Thank you for reporting this issue. I have attempted to reproduce this "hang" myself without success. Would you be able to create a minimal reproduction app? This bug is especially insidious because there are no logs whatsoever produced which makes debugging near impossible. If you can, could you publish this app into GitHub where I can clone it and reproduce the hang? With that, it should be relatively straight-forward to fix. Thank you.

**Comment by GaryAustin1** [comment]
Adding to my comment on @laurentpayot's post.
If I don't turn on persistence 9.0.0 works, 9.0.0-beta.8 works either way.  Not sure if the other two report generators have persistence on or not from their descriptions..

**Comment by laurentpayot** [comment]
@dconeybe I created a minimal reproduction app at https://github.com/laurentpayot/sscce-firebase
…but I could not reproduce the issue, even within a web worker like in my app

@GaryAustin1 you are right, `getDoc()` works if persistence is not enabled. Good to know!

Note that Rollup has a [similar issue](https://github.com/rollup/rollup/issues/4213) that is caused by  the lastest TypeScript version that appeared around the same time as v9. Could the issue  come from the buggy TS version Firebase v9.0.0 was transpiled with?

**Comment by GaryAustin1** [comment]
So I have my case narrowed to the order of setting persistence and ui startup....

`firebase.initializeApp(firebaseConfig)
const firebaseApp = initializeApp( firebaseConfig );
const firestoreDb = getFirestore()

enableIndexedDbPersistence(firestoreDb)    // persistence first does not work
const ui = new firebaseui.auth.AuthUI(firebase.auth())

const unregisterAuthObserver = firebase.auth().onAuthStateChanged(user => {
  console.log("hi")
  console.log("fb initialize")

  const docRef = doc(firestoreDb, "users","7dBFdQoGEGO979tZVMKJ0jJ8a6s1");
  getDoc(docRef).then((docSnap) => {
    if (docSnap.exists()) {
      console.log("Document data:", docSnap.data());
    } else {
       console.log("No userInfo yet");
    }
  })
`

If I move the enableIndexedDbPersistence(firestoreDb)  right after firebaseui.auth it works....
this is with firebaseui@0.600.0 ...

**Comment by schmidt-sebastian** [comment]
@dconeybe I will take a look at this.

**Comment by klausbreyer** [comment]
This occurs for me since 9.0.0 beta 3. I stayed at beta 2 until now.
But I learned through this github issue, that it is caused by the auth. 

But today upgraded  my code and introduced a timeout, to make sure that the auth is resolved, before I am calling getDoc. Without changing anything else, it works again!

**Comment by fuelkoy** [comment]
Is this issue resolved yet as I'm facing it still occuring with firebase@9.0.2.
The issue was still not in firebase@9.0.0-beta.7 but it occured first in firebase@9.0.0 and has been in all version after that as far as I have tested.

**Comment by maxfahl** [comment]
I'm facing the same issue while using Expo v. 42.

**Comment by schmidt-sebastian** [comment]
@maxfahl What version are you using? If you are on the latest version, do you mind sharing debug logs?
