### ISSUE TITLE
Expo and Firestore security rules

### ISSUE THREAD

**Issue by kusaeva** [firebase/firebase-js-sdk#703]
* Operating System version: Android/iOS
  * Firebase SDK version: 4.12.1
  * Firebase Product: firestore

I’m using expo and the firebase web sdk (cause native firebase sdk is not working without detaching expo project).
When I decided to set up firestore security rules like this:
```
service cloud.firestore {
   match /databases/{database}/documents {
     match /{document=**} {
       allow read, write: if request.auth != null;
     }
   }
 }
```

suddenly I got permission-denied. It appears both on Android/iOS
<img width="260" alt="screen shot 2018-04-18 at 21 14 18" src="https://user-images.githubusercontent.com/5486933/38950314-b73072d0-434d-11e8-9b88-6ee665d930d3.png">

User is 100% authorized and I am not the only one who experiences this problem. I found it at StackOverflow, Firebase Google Group, Firebase Slack channel, Expo forums but it seems that no one creates the issue here.
The only solution was suggested at [stackoverflow](https://stackoverflow.com/questions/48054884/firebase-firestore-missing-or-insufficient-permissions-using-expo-react-native) - downgrading firebase sdk to 4.6.2. 
But I really don't like it, it has a problem with firestore on Android and need to be patched.

I understand that using firebase web sdk for Android/iOS is not the case but is there any chance that the issue will be fixed?

**Comment by mikelehen** [comment]
So just to confirm, this happens with 4.12.1 but not 4.6.2?  If you can verify exactly what release the regression occurred in, that will help us track it down.

And can you capture logs by calling `firebase.firestore.setLogLevel('debug')` before calling any other firestore operations?

**Comment by kusaeva** [comment]
I can confirm that security rules work with 4.6.2 and stop working with 4.7.0

```
17:49:18 [exp] Firestore (4.10.1) 2018-04-19T14:49:18.616Z [MemoryPersistence]: Starting transaction: Start LocalStore
17:49:18 [exp] Firestore (4.10.1) 2018-04-19T14:49:18.619Z [MemoryPersistence]: Starting transaction: Get last stream token
17:49:18 [exp] Firestore (4.10.1) 2018-04-19T14:49:18.621Z [MemoryPersistence]: Starting transaction: Get next mutation batch
17:49:18 [exp] Firestore (4.10.1) 2018-04-19T14:49:18.628Z [MemoryPersistence]: Starting transaction: Allocate query
17:49:18 [exp] Firestore (4.10.1) 2018-04-19T14:49:18.629Z [MemoryPersistence]: Starting transaction: Execute query
17:49:18 [exp] Firestore (4.10.1) 2018-04-19T14:49:18.631Z [MemoryPersistence]: Starting transaction: Remote document keys
17:49:18 [exp] Firestore (4.10.1) 2018-04-19T14:49:18.636Z [Connection]: Creating WebChannel: https://firestore.googleapis.com/google.firestore.v1beta1.Firestore/Listen/channel [object Object]
17:49:18 [exp] Firestore (4.10.1) 2018-04-19T14:49:18.644Z [Connection]: Opening WebChannel transport.
17:49:18 [exp] Firestore (4.10.1) 2018-04-19T14:49:18.649Z [Connection]: WebChannel sending: {"database":"projects/subs-dev/databases/(default)","addTarget":{"documents":{"documents":["projects/subs-dev/databases/(default)/documents/users/+11111111111"]},"targetId":2}}
17:49:20 [exp] Firestore (4.10.1) 2018-04-19T14:49:20.169Z [Connection]: WebChannel transport opened.
17:49:21 [exp] Firestore (4.10.1) 2018-04-19T14:49:21.161Z [Connection]: WebChannel received: {"targetChange":{"targetChangeType":"ADD","targetIds":[2]}}
17:49:21 [exp] Firestore (4.10.1) 2018-04-19T14:49:21.162Z [Connection]: WebChannel received: {"targetChange":{"cause":{"code":7,"message":"Missing or insufficient permissions."},"targetChangeType":"REMOVE","targetIds":[2]}}
17:49:21 [exp] Firestore (4.10.1) 2018-04-19T14:49:21.167Z [MemoryPersistence]: Starting transaction: Release query
17:49:27 [exp] Uncaught Error in onSnapshot:, [FirebaseError: Missing or insufficient permissions.]
- node_modules/firebase/node_modules/@firebase/firestore/dist/cjs/src/api/database.js:553:26 in errHandler
- ... 9 more stack frames from framework internals
```

**Comment by mikelehen** [comment]
Thanks for the details. I've been able to reproduce the issue, though I don't know yet what's causing it.  I'll let you know when I know more.

**Comment by mikelehen** [comment]
I found the PR that's seemingly responsible (the problem goes away if I revert it), but I can't figure out why.  :-/  #322 

The issue happens on both Android and iOS, and very suspiciously goes away if I enable the network inspector in the React Native Debugger.  So I think there's probably a bug (or at least behavioral difference) in the React Native networking stack at play, but despite debugging pretty deep I haven't been able to determine what it is. :-/

**Comment by apaatsio** [comment]
I'm having the same problem when using the JS SDK 4.13.1 in the browser (Chrome 67).

```
Firestore (4.9.0) 2018-04-21T20:44:56.167Z [MemoryPersistence]: Starting transaction: Start LocalStore
Firestore (4.9.0) 2018-04-21T20:44:56.169Z [MemoryPersistence]: Starting transaction: Get last stream token
Firestore (4.9.0) 2018-04-21T20:44:56.169Z [MemoryPersistence]: Starting transaction: Get next mutation batch
Firestore (4.9.0) 2018-04-21T20:44:56.172Z [MemoryPersistence]: Starting transaction: Allocate query
Firestore (4.9.0) 2018-04-21T20:44:56.173Z [MemoryPersistence]: Starting transaction: Execute query
Firestore (4.9.0) 2018-04-21T20:44:56.176Z [MemoryPersistence]: Starting transaction: Remote document keys
Firestore (4.9.0) 2018-04-21T20:44:56.179Z [Connection]: Creating WebChannel: https://firestore.googleapis.com/google.firestore.v1beta1.Firestore/Listen/channel [object Object]
Firestore (4.9.0) 2018-04-21T20:44:56.183Z [Connection]: Opening WebChannel transport.
Firestore (4.9.0) 2018-04-21T20:44:56.187Z [Connection]: WebChannel sending: {"database":"projects/foo/databases/(default)","addTarget":{"documents":{"documents":["projects/foo/databases/(default)/documents/users/user123/bar/baz"]},"targetId":2}}
Firestore (4.9.0) 2018-04-21T20:44:57.295Z [Connection]: WebChannel transport opened.
Firestore (4.9.0) 2018-04-21T20:44:58.295Z [Connection]: WebChannel received: {"targetChange":{"targetChangeType":"ADD","targetIds":[2]}}
Firestore (4.9.0) 2018-04-21T20:44:58.297Z [Connection]: WebChannel received: {"targetChange":{"cause":{"code":7,"message":"Missing or insufficient permissions."},"targetChangeType":"REMOVE","targetIds":[2]}}
Firestore (4.9.0) 2018-04-21T20:44:58.300Z [MemoryPersistence]: Starting transaction: Release query
index.js:2178 Uncaught Error in onSnapshot: Error: Missing or insufficient permissions.
    at new FirestoreError (error.js:149)
[full call stack omitted]
```

**Comment by apaatsio** [comment]
@mikelehen Problem solved. I had a mistake in my rules. They were missing the line `match /databases/{database}/documents {`

**Comment by mikelehen** [comment]
I've opened PR https://github.com/firebase/firebase-js-sdk/pull/717 to address this by implementing the workaround of not using $httpHeaders on React Native.

For reference, my investigation up to this point:

* The issue happens on iOS and Android when using $httpHeaders to send our headers via queryparams. The issue goes away if you send the headers as normal headers instead.
* I debugged through the webchannel and React Native code to generate the request and didn't see anything suspicious with the generated URL / request options / etc.
* You can't see network requests from React Native unless you use their "React Native Debugger" and enable "Network Inspect" mode, but that (I think) routes all the network requests through Chrome, and then the issue goes away.
* AFAIK I can't use a network sniffer since the traffic is SSL-encrypted.
* So to see the requests I pointed the webchannel connection at a dummy http localhost server instead of the real Firestore, and just spun up netcat listening on a port in order to capture the requests, but I didn't see any obvious differences that would cause the React Native ones to fail.

So I'm just moving forward with the workaround.

**Comment by llccrr** [comment]
Any news about this work around ? 
Having the issue too :/

**Comment by mikelehen** [comment]
@llccrr Sorry, I need to do a bit of cleanup to that PR and haven't gotten a chance. It should move forward in the next day or two.  Until it lands and releases, you'll probably want to stick with Firebase 4.6.2. Sorry for the inconvenience.

**Comment by mikelehen** [comment]
Okay, my PR was merged and this should be fixed in the next release.

**Comment by llccrr** [comment]
Upgraded to firebase@5.0.2 and I'm still having the issue.
I'm using 
```
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth.uid != null;
    }
  }
}
```
From the Firestore documentation to allow the access to every documents if the user is signed in. 
But I'm still getting: `Missing or insufficient permissions.` from my front-end in react-native.
I am not using expo.
Is it working for you ?

**Comment by mikelehen** [comment]
Thanks for the update. I'm not sure why you had to "yarn remove" / "yarn add" but I'm glad it worked.  I'm closing this issue.  If anybody is seeing this after firebase@5.0.0, let us know.  Thanks!

**Comment by jamesreilly5** [comment]
I was on 4.6.2 for a long time and the other day it magically broke and gave me the same permissions errors. I resolved it by bumping to 5.3.1 but I'd like to understand how this happened. Is it possible that something changed in the Firestore back end to make this suddenly break?
